### ISSUE TITLE
Déployer Application sur le store

### ISSUE THREAD

**Issue by zYmMiJ** [adriens/emploi-nc-app#2]
Déployer l'application sur le store une fois que tous les pré-requis sont OK.

- [x] Nom de l'appli
- [x] Logo
- [x] Covers
- [x] Video de démo tel
- [x] Upload appBundle et saisie des tous les formulaires sur Google Play Console
- [x] Validation par Google et publication publique sur le STore

**Comment by adriens** [comment]
👍

**Comment by HakumenNC** [comment]
Bundle et Apk : :white_check_mark:

**Comment by adriens** [comment]
Mise à jour des screenhsots non mockés
![image](https://user-images.githubusercontent.com/5235127/77262410-bea6be80-6ce9-11ea-8837-f696be5fd2a1.png)

**Comment by adriens** [comment]
@HakumenNC , j'attends la version avec nom-version et j'envoie sur la Google Play Console, y'a encore plein de formulaires à remplir

**Comment by HakumenNC** [comment]
@adriens Noms à jour sur le dépot

**Comment by adriens** [comment]
@HakumenNC tu peux me renvoyer les binaires ?

**Comment by adriens** [comment]
Pour info, instructions suivies de la page : https://flutter.dev/docs/deployment/android pour publication sur le store

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/77264897-6ecaf600-6cef-11ea-8a36-657d841e15a1.png)

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/77265137-10524780-6cf0-11ea-86e4-7cce5aee8fa1.png)

**Comment by adriens** [comment]
Je passe au content rating...

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/77265599-39bfa300-6cf1-11ea-8dc9-5c90ed984d75.png)

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/77265647-5c51bc00-6cf1-11ea-9819-bcc8aaa9fc46.png)

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/77265695-7d1a1180-6cf1-11ea-9a45-f33ccede2900.png)

**Comment by adriens** [comment]
Content rating ✔️ 
![image](https://user-images.githubusercontent.com/5235127/77265730-958a2c00-6cf1-11ea-9776-0d65fd1ef0d7.png)

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/77265957-41337c00-6cf2-11ea-966a-4d16ffbe5d2c.png)

**Comment by adriens** [comment]
Pricing & distribution ✔️ 
![image](https://user-images.githubusercontent.com/5235127/77266024-70e28400-6cf2-11ea-969f-5faefc076120.png)

**Comment by adriens** [comment]
Store listing ✔️ 
![image](https://user-images.githubusercontent.com/5235127/77266081-98d1e780-6cf2-11ea-879e-81aaa9949803.png)

**Comment by adriens** [comment]
Ready to publish ✔️ 
![Uploading image.png…]()

**Comment by adriens** [comment]
Ready to publish
![image](https://user-images.githubusercontent.com/5235127/77266149-c323a500-6cf2-11ea-8b29-178aa7b7ac35.png)

**Comment by adriens** [comment]
Review and rollout
![image](https://user-images.githubusercontent.com/5235127/77266261-1564c600-6cf3-11ea-8b8a-26fd0807bc01.png)

**Comment by adriens** [comment]
Full rollout ✔️ 
![image](https://user-images.githubusercontent.com/5235127/77266308-3a593900-6cf3-11ea-80c1-d345abbf36a3.png)

**Comment by adriens** [comment]
Voila, on est en pending publication:

![image](https://user-images.githubusercontent.com/5235127/77266347-552bad80-6cf3-11ea-91d6-43a2a6a5690f.png)

**Comment by adriens** [comment]
C'est maintenant qu'on attend je pense 10 jours car Google a tout ralenti.

Objectfi atteint 🚀 🎆

**Comment by adriens** [comment]
En attente validation par Google ⏸

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/77363188-5b2e9680-6da6-11ea-81fa-7852fbcb3f99.png)

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/77861322-ec4ab500-725f-11ea-81f1-cfea2a360888.png)


![image](https://user-images.githubusercontent.com/5235127/77861341-100dfb00-7260-11ea-8e1b-59b56d9c4c67.png)


![image](https://user-images.githubusercontent.com/5235127/77861349-1b612680-7260-11ea-959a-a49a44d1d6ac.png)

**Comment by adriens** [comment]
🎆  @zYmMiJ !!!

**Comment by adriens** [comment]
mauvais applicationid, i lfaut :

- [x] Détruire l'appli précédente
- [ ] republier sur le store ( et attendre l'évalutaion de Google)

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/77866915-ab16cd00-7280-11ea-8a37-ae3b2c10f980.png)

**Comment by adriens** [comment]
Je passe en "Pending publication"... rdv dans une semaine.

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/78301897-8757cd80-7585-11ea-83da-31ed8ec3b113.png)


![image](https://user-images.githubusercontent.com/5235127/78301937-98084380-7585-11ea-92d4-173e4cc0a94c.png)

**Comment by adriens** [comment]
https://play.google.com/store/apps/details?id=com.github.adriens.nc.emploi

**Comment by adriens** [comment]
❤️
