### ISSUE TITLE
Ecran Offres/Home - Partie Toutes

### ISSUE THREAD

**Issue by zYmMiJ** [adriens/emploi-nc-app#20]
![mock1](https://user-images.githubusercontent.com/43323367/77972971-9a2c9100-733e-11ea-9a00-535eb094bf0b.png)

Création de l'écran => Toutes les offres : 

- [X] ListCard

- [ ] Timeline

**Comment by adriens** [comment]
Design OK, je propose de fermre

**Comment by zYmMiJ** [comment]
![Toutes](https://user-images.githubusercontent.com/43323367/78514383-be83e400-77fc-11ea-9e7b-d33f089236bd.jpg)

**Comment by adriens** [comment]
👍
