### ISSUE TITLE
Ecran Offres/Home - Partie Récentes

### ISSUE THREAD

**Issue by zYmMiJ** [adriens/emploi-nc-app#21]
![mock2](https://user-images.githubusercontent.com/43323367/77973155-29d23f80-733f-11ea-9ba3-9beeaf8a046a.png)

Création de l'écran Offres Récentes dans un style gallery ou affiche de cinéma.

**Comment by zYmMiJ** [comment]
![recentes](https://user-images.githubusercontent.com/43323367/78514355-96948080-77fc-11ea-889a-67e69c2acb12.jpg)

**Comment by adriens** [comment]
Super stylé 👏
