### ISSUE TITLE
Ecran A Propos - Partie A Propos

### ISSUE THREAD

**Issue by zYmMiJ** [adriens/emploi-nc-app#22]
![mock3](https://user-images.githubusercontent.com/43323367/77973364-a6651e00-733f-11ea-8ec6-d78ef1dd0cb0.png)

Création de l'écran à propos : 

- Logo
- Nom de l'application
- QRCode vers le store
- Numéro de version
- Courte description de l'application

**Comment by adriens** [comment]
Screenshot ?

**Comment by zYmMiJ** [comment]
![about1](https://user-images.githubusercontent.com/43323367/78514330-795fb200-77fc-11ea-9459-b3559e9bdba0.jpg)
![about2](https://user-images.githubusercontent.com/43323367/78514332-7a90df00-77fc-11ea-95cc-0840f16f20ac.jpg)

**Comment by adriens** [comment]
Magnifique, excellent 🎆
