### ISSUE TITLE
Ecran A Propos - Partie Collaborateur

### ISSUE THREAD

**Issue by zYmMiJ** [adriens/emploi-nc-app#23]
![mock4 1](https://user-images.githubusercontent.com/43323367/77973613-75391d80-7340-11ea-8a39-47b441765584.png)
![mock4](https://user-images.githubusercontent.com/43323367/77973616-766a4a80-7340-11ea-936b-800e607cb475.png)

Création de l'écran collaborateurs soit en : 

- Slide (préférence pour slide pour l'instant)

- Liste

**Comment by adriens** [comment]
Screenshot ?

**Comment by zYmMiJ** [comment]
![collaborateurs](https://user-images.githubusercontent.com/43323367/78514293-51704e80-77fc-11ea-9e18-db9108f6e007.jpg)

**Comment by adriens** [comment]
# Description

Typo: Adrien **Sales** et non pas Sal**è**s

# Action

1. Supprimer l'accent sur le dernier e

**Comment by zYmMiJ** [comment]
Dsl

![collaborateurs (2)](https://user-images.githubusercontent.com/43323367/78514758-b2992180-77fe-11ea-8207-f4e50a08fa99.jpg)

**Comment by adriens** [comment]
👍
