### ISSUE TITLE
Ecran A Propos - Partie Social

### ISSUE THREAD

**Issue by zYmMiJ** [adriens/emploi-nc-app#24]
Création de l'écran Social

**Comment by zYmMiJ** [comment]
![social](https://user-images.githubusercontent.com/43323367/78514275-37cf0700-77fc-11ea-81d3-c79074f08037.jpg)

**Comment by adriens** [comment]
Chaîne youtube : pas en cours, mettre cette url:

https://www.youtube.com/playlist?list=PLVaySOddZPMer1H6o234RyWhEfSThuYW5

**Comment by zYmMiJ** [comment]
![social (2)](https://user-images.githubusercontent.com/43323367/78514753-a90fb980-77fe-11ea-8771-8c036aa0d1ca.jpg)

**Comment by adriens** [comment]
Quand on clique ça ouvre bien la chaîne youtube ❔

**Comment by zYmMiJ** [comment]
Yep

**Comment by adriens** [comment]
👍

**Comment by zYmMiJ** [comment]
https://drive.google.com/file/d/14eEd5lHES2PAhRi4YkZJP9ZzZZNJFrbW/view?usp=drivesdk
