### ISSUE TITLE
Ecran Stats

### ISSUE THREAD

**Issue by zYmMiJ** [adriens/emploi-nc-app#25]
![mock5](https://user-images.githubusercontent.com/43323367/77973931-62731880-7341-11ea-8aad-4e97b1d5d3a4.png)

Création de l'écran Stats

**Comment by adriens** [comment]
Le design est tvraiment excellent ! Très bien vu pour l'animation 👏

**Comment by zYmMiJ** [comment]
![stats](https://user-images.githubusercontent.com/43323367/78514246-18d07500-77fc-11ea-969a-469f1c20a64b.jpg)

**Comment by adriens** [comment]
Super clean. 💯
