### ISSUE TITLE
Mes offres préférées

### ISSUE THREAD

**Issue by adriens** [adriens/emploi-nc-app#28]
Etre capable de flagger (et déflagger comme sur Gmail) une offre comme préférée afin de pouvoir la retrouver facilement plus tard via mon menu des offres favorites, ou encore un filtre

**Comment by zYmMiJ** [comment]
J'ai changer le layout du home/récentes et j'y ai ajouter l'emplacement pour les offres préférés, on peut reprendre le meme layout pour d'autres catégories ... 

Je commence le fonctionnement like/dislike.

(Données provenant des dernières offres et non des likes pour l'instant)

![SVID_20200507_143818_1](https://user-images.githubusercontent.com/43323367/81252421-9db7e400-9071-11ea-96eb-1582b83a1a4e.gif)

**Comment by adriens** [comment]
Très bonne idée de les showcaser comme ça.

Typo sur "Annoncées likés" : **likées**

**Comment by adriens** [comment]
Mais la vue en mode défilé permanent des dernières offres est à retenir par exemple pour la page d'accuieil. Ca permet d'en mettre plus, c'est très attrayant ❣️

**Comment by zYmMiJ** [comment]
Problème de Front recharge des images visible lors d'un ajout aux favoris.
Utilisation d'un widget future pour récupérer les infos dans le cache et les afficher.
Lors d'un ajout d'un favoris changement en bdd locale via des requetes.
Changement de l'icone via un booléens stocké en bdd qu'on met à jour via un setState qui provoque un rechargement du future et donc des images.
![SVID_20200513_135733_1](https://user-images.githubusercontent.com/43323367/81766735-6ab69a00-9522-11ea-9028-9ebcea1b07f9.gif)
