### ISSUE TITLE
Nom Application

### ISSUE THREAD

**Issue by zYmMiJ** [adriens/emploi-nc-app#3]

**Comment by adriens** [comment]
👍

**Comment by adriens** [comment]
`Offres Emplois Calédonie` ❔

**Comment by adriens** [comment]
**OK, On part donc sur `Offres Emplois Calédonie`** 👏

**Comment by adriens** [comment]
Mis à jour dans le `README`
Plus qu'à mettre à jour dans le projet @zYmMiJ
