### ISSUE TITLE
Partager une annonce

### ISSUE THREAD

**Issue by adriens** [adriens/emploi-nc-app#31]
# Description

Lorsque positionné sur une annonce, permettre de la partager très facilement avec une tierce personne

# Business case

Je cherche une annonce pour quelqu'un avec mon appli et j'en vois une intéressante: je veux la lui partager.
Je clique sur partager et là, plusieurs options:

- par mail: ça ouvre mon mailer par défaut et charge l'url de l'annonce avec un message...et dans le footer on met le lien de l'appli mobile sur le store
- QrCode: je montre le QrCode à la tierce personne qui flashe. Dans le QrCode: url de l'annonce

**Comment by zYmMiJ** [comment]
Exemple de différents rendu de la fonctionnalités partage : 

![shareSocial](https://user-images.githubusercontent.com/43323367/81126153-31ac8180-8f86-11ea-83a9-319d0892a411.png)

**Comment by zYmMiJ** [comment]
Lorsqu'on ajoute une image et du texte le rendu diffère selon les plateformes, il peut  même avoir des pertes de données, je testerai avec un autre package de partage si il existe un meilleur.

Pour l'instant je partage du texte et des liens avec leurs previews car c'est le plus fiable (moins/pas de perte de données).

**Comment by adriens** [comment]
Yep, c'est très bien comme ça @zYmMiJ  👍

**Comment by zYmMiJ** [comment]
![Screenshot_20200505_154504_com github adriens nc emploi (1)](https://user-images.githubusercontent.com/43323367/81131729-d3889a00-8f97-11ea-8386-97b893d3159f.jpg)

**Comment by zYmMiJ** [comment]
![Screenshot_20200506_124611_com github adriens nc emploi](https://user-images.githubusercontent.com/43323367/81131750-ec914b00-8f97-11ea-9152-53e5b2c917f1.jpg)
