### ISSUE TITLE
Tear down refresh

### ISSUE THREAD

**Issue by adriens** [adriens/emploi-nc-app#33]
Sur tout écran liée à la rechercher, y compris celui d'accueil avec les 4 offres, permettre de refresh en mode tear down comme sur les réséeaux sociaux pour avoir les toutes dernières news 😄

**Comment by zYmMiJ** [comment]
Liens utiles : 

- https://pub.dev/packages/pull_to_refresh

- https://enappd.com/blog/building-flutter-pulltorefresh/57/

**Comment by zYmMiJ** [comment]
![Screenshot_20200505_154517_com github adriens nc emploi](https://user-images.githubusercontent.com/43323367/81035685-c4e2aa00-8ee7-11ea-98db-4566f0302359.jpg)
![Screenshot_20200505_154504_com github adriens nc emploi](https://user-images.githubusercontent.com/43323367/81035690-cf04a880-8ee7-11ea-9334-610aeb029266.jpg)

**Comment by zYmMiJ** [comment]
https://github.com/adriens/emploi-nc-app/issues/33#issuecomment-623854777

Premier visuel tear down : scroll vers le haut recharge les 10 dernières annonces et les insèrent dans notre cache local si pas de nouvelles annonces : pas d'insertion.

Si **plus de 10 nouvelles annonces** alors ajoute et affiche que les 10 dernières.

Bouton `charger plus` non fonctionnelle pour le moment.

**Comment by adriens** [comment]
Très bonne stratégie pour la gestion du cache. Bien joué 👍

**Comment by zYmMiJ** [comment]
cf 9d17e6420f17482c2a980125885470e17f8d6b66
