### ISSUE TITLE
Gérer un cache local

### ISSUE THREAD

**Issue by adriens** [adriens/emploi-nc-app#35]
ETudier la gestion d'un cache local afin d'avoir une expérience optimale sur un volume maximal de contenu

**Comment by zYmMiJ** [comment]
Choix possible pour l'instant : 

- [x] sqlite 

Liens utiles : 
   
- https://medium.com/swlh/flutter-get-data-from-a-rest-api-and-save-locally-in-a-sqlite-database-9a9de5867939 

- [ ] sqlite et synchro d'une même bdd avec firebase

- [ ] local storage

**Comment by zYmMiJ** [comment]
![Screenshot_20200504_135258_com github adriens nc emploi](https://user-images.githubusercontent.com/43323367/80933353-123f1880-8e0f-11ea-8d76-94e1375e3fa0.jpg)

Problème  :   

Je ne peut charger plus de X offres en memes temps dans la base, l'api plante.

Proposition : 

- [ ] Charger les données par paquet lors du premier lancement de l'application, puis au fur et à mesure.

- [ ] Charger les données sans les images et puis tester la limite . Stocker les images ailleurs que dans l'api ou via un autre appel individuel (du genre : logo/numeroOffre/) puis les charger dans l'application via internet.

- [ ] Insérer les données dans notre cache local à chaque actions : recherche, tear down etc ...

- [ ] Autres
