### ISSUE TITLE
Page des stats rognée sur le bas (si on ne scroll pas)

### ISSUE THREAD

**Issue by adriens** [adriens/emploi-nc-app#40]
![image](https://user-images.githubusercontent.com/5235127/79505620-619bef80-8080-11ea-8e7d-ae2d926f7354.png)

**Comment by adriens** [comment]
En diminuant un peu la taille des chiffres/icones, ça passe tranquille

**Comment by zYmMiJ** [comment]
cf 4188f44d097303805b6f4d202f244bfff019c803

A confirmez sur vos mobiles mais ca devrait etre bon.
