### ISSUE TITLE
pas d'option partage sur une annonce cherchée

### ISSUE THREAD

**Issue by adriens** [adriens/emploi-nc-app#50]
1. Aller sur accueil
2. Chercher une annonce
3. Voir l'annonce
4. Ne pas trouver le bouton de partage

**Comment by adriens** [comment]
je confirme, y'a pas l'option de partage sur une annonce cherchée avec ce scénario

![Screenshot_20200706-190436](https://user-images.githubusercontent.com/5235127/86570463-ac604000-bfbb-11ea-8da1-cecddfa66c42.jpg)

**Comment by zYmMiJ** [comment]
cf 4fa1c3d2a692977d41a179b6c2a15976fda76e58

**Comment by adriens** [comment]
fixée par #54
