### ISSUE TITLE
Déployer la  1.2.1 sur le store

### ISSUE THREAD

**Issue by adriens** [adriens/emploi-nc-app#54]
- [x] release la  `1.2.1` (@zJimmyz )
- [x] builder et signer le appBundle (@HakumenNC ) et le mettre à dispo de @adriens 
- [x] Effectuer le rollout de cette nouvelle release sur le store: @adriens 
- [x] Annoncer la dispo de la nouvelle version avec un GIF sur linkedIn: @adriens

**Comment by HakumenNC** [comment]
> builder et signer le appBundle (@HakumenNC ) et le mettre à dispo de @adriens

✔️

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/87845530-ffb78400-c913-11ea-8b2c-8a34aabd42e8.png)

**Comment by adriens** [comment]
✔️ 
![image](https://user-images.githubusercontent.com/5235127/87846242-2678b900-c91a-11ea-894e-221519bf1c62.png)

**Comment by adriens** [comment]
mise à jour sur tel en cours...

**Comment by adriens** [comment]
L'optin de partage est bien là 👏 
Je vais cogiter pour un petit GIF qui envoie du pâté 🤣

**Comment by adriens** [comment]
https://www.linkedin.com/posts/adrien-sales_emploi-nc-recherche-d%C3%A9v-java-activity-6690912752715862016-ZpMX
