### ISSUE TITLE
Données sur l'appli mobile

### ISSUE THREAD

**Issue by adriens** [adriens/emploi-nc-app#57]
# Contexte

Montrer que même si les bénéfices directs et indirects de l'open data sont durs à évaluer,
on a quelques success stories de réutilisations.

# Actions

Fournir les chiffres donnant : 

- [x] Nb d'applications installées
- [x] Nb d'usagers par jour
- [x] Et tout autre statistique intéressante

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/132628409-5aea4885-9b9f-40b3-a7a4-4a7c0d66d18e.png)


![image](https://user-images.githubusercontent.com/5235127/132628453-375a1561-75c7-42d5-931f-f1b495c9c0be.png)

![image](https://user-images.githubusercontent.com/5235127/132628634-4bb8bbe6-8379-452d-b84b-57b155f5c600.png)

![image](https://user-images.githubusercontent.com/5235127/132628693-426b822b-6142-4e9b-bf90-7dfd3da6d9ef.png)

![image](https://user-images.githubusercontent.com/5235127/132628742-49a3eccf-2390-464a-8a5a-85d35ff80790.png)

[New Caledonia, France.csv](https://github.com/adriens/emploi-nc-app/files/7133679/New.Caledonia.France.csv)
[Change analysis.csv](https://github.com/adriens/emploi-nc-app/files/7133683/Change.analysis.csv)

![image](https://user-images.githubusercontent.com/5235127/132629186-daf95d60-a545-4279-8fb5-89f64aecab64.png)

[DAU_MAU__2021_8_10-2021_9_8.csv](https://github.com/adriens/emploi-nc-app/files/7133703/DAU_MAU__2021_8_10-2021_9_8.csv)

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/132629507-36b0acc0-5e99-487c-9119-a01137d6ae3e.png)


![image](https://user-images.githubusercontent.com/5235127/132629590-78436811-e8dd-49f5-9330-93a9c60a2039.png)

**Comment by adriens** [comment]
Voila j'ai sorti tout ce que je pouvais

**Comment by houysy** [comment]
Merci pour ces statistiques!
C'est encourageant de constater que l'open data permet en effet de rendre service à tous , notamment grâce aux personnes motivées qui utilisent la data pour en faire des applications innovantes.

**Comment by houysy** [comment]
@adriens , il me semble que les statistiques présentent surtout les installations de l'application.
Est-ce qu'il y a le nombre d'utilisateurs par jour ? 
Est-ce que les "129 devices actifs par jour" correspondent aux utilisateurs journaliers ?

**Comment by adriens** [comment]
Hello @houysy , voici chaque élément avec davantage de détails, qui devraient répondre à tes questions, tu me diras.

> Est-ce qu'il y a le nombre d'utilisateurs par jour 

# Nb utilisateurs par jour

![image](https://user-images.githubusercontent.com/5235127/132772810-3849f6ff-d488-4591-95fe-8c28b0d596b3.png)

# Nouvelles installations

![image](https://user-images.githubusercontent.com/5235127/132772952-8aaa9a3c-b520-4338-abb9-3521a1c99248.png)


# Installations totales

![image](https://user-images.githubusercontent.com/5235127/132773013-4dfe844c-fdd4-4fe1-9c7b-a710f5f31be5.png)


# Visites de l'app sur le store

![Uploading image.png…]()

**Comment by houysy** [comment]
Super, merci pour les précisions!

**Comment by adriens** [comment]
De rien c'est un réel plaisir 😸
