### ISSUE TITLE
Ressources de Démo sur tablette Tablette

### ISSUE THREAD

**Issue by zYmMiJ** [adriens/emploi-nc-app#6]
- [x] Screenshots (un pour chaque use case, : icône sur bureau puis un par écran, y compris page du gouv dans navigateur). Pour le screenshot icone, essayer de l'isoler sur un écran vierge et de mettre un joli wallpaper qu irappelle notre beau pays 😍 
- [x] video de démo qui embarque les cas d'utilisations en one shote. Essyer de faire durer > 30 s

**Comment by adriens** [comment]
👍

**Comment by adriens** [comment]
Ok, je prends

**Comment by adriens** [comment]
C'est parti 😸 On va avoir une nouvelle cagougeekette dans le projet !

**Comment by tatlaviolette** [comment]
voilà les premiers screenshots... 
![Screenshot_20200324-095342](https://user-images.githubusercontent.com/62575911/77372097-02b4c480-6db9-11ea-8f95-93322ea2ad13.png)
![Screenshot_20200324-095500](https://user-images.githubusercontent.com/62575911/77372106-07797880-6db9-11ea-928c-6f4770e60b62.png)
![Screenshot_20200324-095557](https://user-images.githubusercontent.com/62575911/77372109-09dbd280-6db9-11ea-9296-484093431254.png)
![Screenshot_20200324-093710](https://user-images.githubusercontent.com/62575911/77372110-0b0cff80-6db9-11ea-9dca-f5573f195113.png)

**Comment by adriens** [comment]
Je charge les screenshots tablette sur le store...

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/77373418-5248bf80-6dbc-11ea-93ed-e1c833a4b23f.png)

**Comment by adriens** [comment]
Ok pour tablette 10' ✔️

**Comment by adriens** [comment]
Merci @tatlaviolette  pour la contribution 🎆
