### ISSUE TITLE
Implémenter un thème switcher pour basculer selon ses préférences

### ISSUE THREAD

**Issue by adriens** [adriens/emploi-nc-app#9]

**Comment by adriens** [comment]
![Screenshot_20200320_165348_com github adriens](https://user-images.githubusercontent.com/5235127/77140372-84f96c00-6acd-11ea-81e7-ea2d920a10a3.jpg)
![Screenshot_20200320_165406_com github adriens](https://user-images.githubusercontent.com/5235127/77140373-862a9900-6acd-11ea-8d1e-c335b6fde6e4.jpg)
![Screenshot_20200320_165615_com github adriens](https://user-images.githubusercontent.com/5235127/77140374-862a9900-6acd-11ea-93eb-d46d27bab5b5.jpg)
![Screenshot_20200320_165806_com github adriens(1)](https://user-images.githubusercontent.com/5235127/77140375-86c32f80-6acd-11ea-9ee6-e3eb3ec493bf.jpg)
![Screenshot_20200320_165806_com github adriens](https://user-images.githubusercontent.com/5235127/77140377-875bc600-6acd-11ea-9e61-69c27f093eeb.jpg)
![Screenshot_20200320_165822_com github adriens(1)](https://user-images.githubusercontent.com/5235127/77140378-875bc600-6acd-11ea-95e7-41e756906320.jpg)
![Screenshot_20200320_165822_com github adriens](https://user-images.githubusercontent.com/5235127/77140379-87f45c80-6acd-11ea-807f-1b5840896049.jpg)
![Screenshot_20200320_165850_com github adriens(1)](https://user-images.githubusercontent.com/5235127/77140381-888cf300-6acd-11ea-9152-e85d5e851b70.jpg)
![Screenshot_20200320_165850_com github adriens](https://user-images.githubusercontent.com/5235127/77140382-888cf300-6acd-11ea-89a4-3751fa611d08.jpg)
![Screenshot_20200320_165918_com github adriens(1)](https://user-images.githubusercontent.com/5235127/77140383-89258980-6acd-11ea-85b1-f3612ca3a18f.jpg)
![Screenshot_20200320_165918_com github adriens](https://user-images.githubusercontent.com/5235127/77140384-89258980-6acd-11ea-9155-9b7bb6750c04.jpg)
![Screenshot_20200320_165330_com github adriens](https://user-images.githubusercontent.com/5235127/77140385-89be2000-6acd-11ea-9438-064181e74048.jpg)

**Comment by zYmMiJ** [comment]
![SVID_20200507_091343_1](https://user-images.githubusercontent.com/43323367/81234558-bf4ea680-9044-11ea-90fe-36971433a45b.gif)

Le thème switcher ps: j'ai changé l'icon et le texte en paramètres dans les menus.

**Comment by adriens** [comment]
Excellent, très bien joué ! Bravo pour le super boulot et à très bientôt.
